config/routes.rb
TodoManager::Application.routes.draw do
  devise_for :users
  resources :tasks do
    post :share, :on => :member
    get :share_form, :on => :member
  end
  resources :showtasks
  root to: "showtasks#index"
end

app/models/showtask.rb
class Showtask < ActiveRecord::Base
  attr_accessible :shared, :sharer_id, :task_id, :user_id, :sharer, :user, :task
  belongs_to :user
  belongs_to :task
  belongs_to :sharer, :foreign_key => "sharer_id", :class_name => "User"

  scope :with_tasks, includes(:task)
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :title

  has_many :showtasks, :dependent => :destroy
  has_many :users, :through => :showtasks

  def share(to_email, by_user)
    user = User.find_by_email(to_email)
    if user
      unless user.tasks.include?(self)
        Showtask.create(
          :task => self,
          :user => user,
          :sharer => by_user,
          :shared => true
        )
      else
        error = "This user (#{to_email}) already has access to this task"
      end
    else
      error = "User with such email not found"
    end
    error
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates_uniqueness_of :email
  validates_confirmation_of :password, :on => :create
  validates_presence_of :password, :email, :on => :create

  has_many :showtasks
  has_many :tasks, :through => :showtasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/showtasks_controller.rb
class ShowtasksController < InheritedResources::Base
  before_filter :authenticate_user!
  def index
    @showtasks = current_user.showtasks.with_tasks
  end

  def destroy
    # TODO check if user can manage this task
    super do |format|
      format.html { redirect_to root_url, :notice => "Shared task deleted successfully" }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  before_filter :authenticate_user!
  def index
    @tasks = current_user.tasks
  end

  def update
    # TODO check if user can manage this task
    super do |format|
      format.html { redirect_to root_url }
    end
  end

  def create
    @task = Task.new(params[:task])
    current_user.tasks << @task
    super do |format|
      format.html { redirect_to root_url }
    end
  end

  def destroy
    # TODO check if user can manage this task
    super do |format|
      format.html { redirect_to root_url }
    end
  end

  def edit
    super do |format|
      format.html { render layout: false }
    end
  end

  def share
    # TODO check if user can manage this task
    email = params[:email]
    @task = Task.find(params[:id])
    error = @task.share(email, current_user)
    if error
      flash[:error] = error
    else
      flash[:notice] = "Task successfully shared to #{email}"
    end
    redirect_to root_url
  end

  def share_form
    @task = Task.find(params[:id])
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def twitterized_type(type)
    case type
      when :alert then "alert-block"
      when :error then "alert-error"
      when :notice then "alert-info"
      when :success then "alert-success"
      else type.to_s
    end
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TODO Manager
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      #navigation
        %ul.nav.nav-pills.pull-right
          %li.active
            %a{:href => "home"} Home
          - if user_signed_in?
            %li
              = link_to "Log Out", destroy_user_session_path, :method => :delete
        %h3.muted TODO manager
      = render 'shared/flashes'
      %hr
      = yield

app/views/shared/_flashes.html.haml
- flash.each do |type, message|
  %div.alert{ "data-alert" => "alert", :class => twitterized_type(type) }
    %a.close{:href => "#", "data-dismiss" => "alert"} ×
    %p= message

app/views/showtasks/_form.html.haml
= form_for task, :html => {:class => "form-horizontal"} do |f|
  .modal-header
    %h3 TODO item
  .modal-body
    .control-group
      %label.control-label{:for => :title} Title
      = f.text_field :title
    .control-group
      %label.control-label{:for => :description} Description
      = f.text_area :description
  .modal-footer
    %button.btn.btn-primary Save

app/views/showtasks/_tasks_table.html.haml
- if @showtasks.empty?
  %h3.muted You have empty TODO list.
- else
  .page-header Your TODO list
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Created At
        %th Title
        %th Description
        %th Actions
    %tbody
      - @showtasks.each do |showtask|
        %tr
          %td= showtask.task.id
          %td= showtask.task.created_at
          %td= showtask.task.title
          %td= showtask.task.description
          %td
            = link_to "Edit", edit_task_path(showtask.task), :class => "btn btn-primary", :data => { :toggle => "modal" }
            - if showtask.shared
              = link_to "Delete from list", showtask_path(showtask), :method => :delete, :class => "btn btn-danger", :confirm => "Delete?"
              %br
              %span.label.label-warning shared by #{showtask.sharer.email}
            - else
              = link_to "Delete", task_path(showtask.task), :method => :delete, :class => "btn btn-danger", :confirm => "Delete?"
              = link_to "Share", share_form_task_path(showtask.task), :class => "btn btn-warning", :data => { :toggle => "modal" }
  :javascript
    setAjaxModal();

app/views/showtasks/edit.html.haml
= render 'form', :task => @task

app/views/showtasks/index.html.haml
%a#add-new-task.btn.btn-primary{:href => "#create-task-modal", :role => :button, :data => {:toggle => "modal"}} Add new task

#tasks-table
  = render 'tasks_table'

#edit-task-modal.modal.hide.fade{:role => :dialog}
#create-task-modal.modal.hide.fade{:role => :dialog}
  = render 'form', :task => Task.new

app/views/showtasks/index.js.haml
:plain
  $("#tasks-table").html("#{escape_javascript(render 'tasks_table')}")

app/views/tasks/_tasks_table.html.haml
- if @tasks.empty?
  %h3.muted You have empty TODO list.
- else
  .page-header Your TODO list
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Created At
        %th Title
        %th Description
        %th Actions
    %tbody
      - @tasks.each do |task|
        %tr
          %td= task.id
          %td= task.created_at
          %td= task.title
          %td= task.description
          %td
            = link_to "Edit", edit_task_path(task), :class => "btn btn-primary", :data => { :toggle => "modal" }
            = link_to "Delete", task_path(task), :method => :delete, :class => "btn btn-danger", :confirm => "Delete?"
  :javascript
    setAjaxModal();

app/views/tasks/share_form.html.haml
= form_tag share_task_path(@task), :class => "form-horizontal" do |f|
  .modal-header
    %h3 Enter email to share task
  .modal-body
    .control-group
      %label.control-label{:for => :email} Email
      = text_field_tag :email
  .modal-footer
    %button.btn.btn-primary Share